# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: ''
        # Default value if no value is explicitly provided
        default: 'build'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: checkout
      uses: actions/checkout@v2.4.2
      with:
        ref: shuang/build
    - name: enter the shell
      run: make shell
    - name: test fpm
      run: pwd && which fpm
    - name: create tmp directoy
      run: mkdir /tmp/istio-release
    - name: go build
      run: STEP=1 go run main.go build --manifest example/manifest.yaml
    - name: validate
      run: go run main.go validate --release /tmp/istio-release/out
    - uses: actions/upload-artifact@v3
      with:
        name: istio-docker
        path: /tmp/istio-release/out/docker
