# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: ''
        # Default value if no value is explicitly provided
        default: 'build'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: checkout
      uses: actions/checkout@v2.4.2
      with:
        ref: shuang/build
    - name: create directory
      run: mkdir /tmp/istio-release
    - name: start the container
      run: make shell
    - uses: actions/upload-artifact@v3
      with:
        name: istio-docker
        path: /tmp/istio-release/out/docker/${{ github.event.inputs.name }}*
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: load image
      run: for i in `ls /tmp/istio-release/out/docker/pilot*`;do docker load -i $i && docker push shawnlu/${{ github.event.inputs.name }} -a;done
